using Content.Shared._ES.Chat;
using Content.Shared.Chat;
using Content.Shared.CCVar;
using JetBrains.Annotations;
using Robust.Shared.Utility;
using Robust.Shared.Configuration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.UserInterface.Systems.Chat.Controls;

[GenerateTypedNameReferences]
public sealed partial class ChannelFilterPopup : Popup
{
    [Dependency] private IPrototypeManager _prototype = default!;

    private readonly Dictionary<ProtoId<ESChatChannelFilterPrototype>, ChannelFilterCheckbox> _filterStates = new();

    public event Action<ProtoId<ESChatChannelFilterPrototype>, bool>? OnChannelFilter;
    public event Action<string>? OnNewHighlights;

    public ChannelFilterPopup()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        HighlightButton.OnPressed += HighlightsEntered;
        // Add a placeholder text to the highlights TextEdit.
        HighlightEdit.Placeholder = new Rope.Leaf(Loc.GetString("hud-chatbox-highlights-placeholder"));

        // Load highlights if any were saved.
        var cfg = IoCManager.Resolve<IConfigurationManager>();
        string highlights = cfg.GetCVar(CCVars.ChatHighlights);

        if (!string.IsNullOrEmpty(highlights))
        {
            UpdateHighlights(highlights);
        }
    }

    public bool IsActive(ProtoId<ESChatChannelPrototype> channel)
    {
        return _filterStates.TryGetValue(_prototype.Index(channel).FilterCategory, out var checkbox) && checkbox.Pressed;
    }

    [PublicAPI]
    public void SetActive(ProtoId<ESChatChannelFilterPrototype> channel, bool isActive)
    {
        if (_filterStates.TryGetValue(channel, out var checkbox) && checkbox.Pressed != isActive)
        {
            checkbox.Pressed = isActive;
            OnChannelFilter?.Invoke(checkbox.Channel, checkbox.Pressed);
        }
    }
    public void SetAllActive(bool isActive)
    {
        foreach (var filter in _filterStates.Keys)
        {
            SetActive(filter, isActive);
        }
    }

    public List<ProtoId<ESChatChannelFilterPrototype>> GetFilteredChannels()
    {
        var channels = new List<ProtoId<ESChatChannelFilterPrototype>>();
        foreach (var (channel, box) in _filterStates)
        {
            if (!box.Pressed)
                channels.Add(channel);
        }

        return channels;
    }

    public void SetChannels()
    {
        var filters = _prototype.EnumeratePrototypes<ESChatChannelFilterPrototype>();
        foreach (var filter in filters)
        {
            if (!_filterStates.TryGetValue(filter, out var checkbox))
            {
                checkbox = new ChannelFilterCheckbox(filter);
                _filterStates.Add(filter, checkbox);
                checkbox.OnPressed += CheckboxPressed;
                checkbox.Pressed = true;
            }

            // TODO: do an extra level to check if we even have access to any channels w/ this filter
            // if ((channels & channel) == 0)
            // {
            //     if (checkbox.Parent == FilterVBox)
            //     {
            //         FilterVBox.RemoveChild(checkbox);
            //     }
            // }
            if (checkbox.IsHidden)
            {
                FilterVBox.AddChild(checkbox);
            }
        }
    }

    public void UpdateHighlights(string highlights)
    {
        HighlightEdit.TextRope = new Rope.Leaf(highlights);
    }

    private void CheckboxPressed(ButtonEventArgs args)
    {
        var checkbox = (ChannelFilterCheckbox) args.Button;
        OnChannelFilter?.Invoke(checkbox.Channel, checkbox.Pressed);
    }

    private void HighlightsEntered(ButtonEventArgs args)
    {
        OnNewHighlights?.Invoke(Rope.Collapse(HighlightEdit.TextRope));
    }

    public void UpdateUnread(ProtoId<ESChatChannelFilterPrototype> channel, int? unread)
    {
        if (_filterStates.TryGetValue(channel, out var checkbox))
            checkbox.UpdateUnreadCount(unread);
    }
}
