using Content.Client.UserInterface.Systems.Chat.Controls;
using Content.Shared._ES.Chat;
using Content.Shared.Chat;
using Content.Shared.Input;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Input;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client.UserInterface.Systems.Chat.Widgets;

[GenerateTypedNameReferences]
[Virtual]
public partial class ChatBox : UIWidget
{
    [Dependency] protected IEntityManager EntManager = default!;
    [Dependency] private ILogManager _log = default!;

    protected readonly ISawmill Sawmill;
    protected readonly ChatUIController Controller;

    public bool Main { get; set; }

    public ProtoId<ESChatChannelPrototype> SelectedChannel => ChatInput.ChannelSelector.SelectedChannel;

    public ChatBox()
    {
        RobustXamlLoader.Load(this);
        Sawmill = _log.GetSawmill("chat");

        ChatInput.Input.OnTextEntered += OnTextEntered;
        ChatInput.Input.OnKeyBindDown += OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged += OnTextChanged;
        ChatInput.Input.OnFocusEnter += OnFocusEnter;
        ChatInput.Input.OnFocusExit += OnFocusExit;
        ChatInput.ChannelSelector.OnChannelSelect += OnChannelSelect;
        ChatInput.FilterButton.Popup.OnChannelFilter += OnChannelFilter;
        Controller = UserInterfaceManager.GetUIController<ChatUIController>();
        Controller.MessageAdded += OnMessageAdded;
        Controller.RegisterChat(this);
    }

    private void OnTextEntered(LineEditEventArgs args)
    {
        Controller.SendMessage(this, SelectedChannel);
    }

    protected virtual void OnMessageAdded(ESChatMessage msg)
    {
        Sawmill.Debug($"{msg.Channel}: {msg.Content}");

        // TODO: chat filters
        /*
        if (!ChatInput.FilterButton.Popup.IsActive(msg.Channel))
        {
            return;
        }
        */

        // TODO:
        /*
        if (msg is { Read: false, AudioPath: { } })
            EntManager.System<AudioSystem>().PlayGlobal(msg.AudioPath, Filter.Local(), false, AudioParams.Default.WithVolume(msg.AudioVolume));
        */

        msg.Read = true;

        AddLine(msg.FormattedMessage, msg.Color);
    }

    private void OnHighlightsUpdated(string highlights)
    {
        ChatInput.FilterButton.Popup.UpdateHighlights(highlights);
    }

    private void OnChannelSelect(ProtoId<ESChatChannelPrototype> channel)
    {
        Controller.UpdateSelectedChannel(this);
    }

    public virtual void Repopulate()
    {
        Contents.Clear();

        foreach (var message in Controller.History)
        {
            OnMessageAdded(message.Item2);
        }
    }

    protected virtual void OnChannelFilter(ChatChannel channel, bool active)
    {
        Contents.Clear();

        foreach (var message in Controller.History)
        {
            OnMessageAdded(message.Item2);
        }

        if (active)
        {
            Controller.ClearUnfilteredUnreads(channel);
        }
    }

    public void AddLine(string message, Color color)
    {
        var formatted = new FormattedMessage(3);
        formatted.PushColor(color);
        formatted.AddMarkupOrThrow(message);
        formatted.Pop();
        Contents.AddMessage(formatted, tagsAllowed: null);
    }

    public void Focus(ProtoId<ESChatChannelPrototype>? channel = null)
    {
        var input = ChatInput.Input;
        var selectStart = Index.End;

        if (channel != null)
            ChatInput.ChannelSelector.Select(channel.Value);

        input.IgnoreNext = true;
        input.GrabKeyboardFocus();

        input.CursorPosition = input.Text.Length;
        input.SelectionStart = selectStart.GetOffset(input.Text.Length);
    }

    public void CycleChatChannel(bool forward)
    {
        // TODO: Chat cycling is FUCKED UP
        // var idx = Array.IndexOf(ChannelSelectorPopup.Ch, SelectedChannel);
        // do
        // {
        //     // go over every channel until we find one we can actually select.
        //     idx += forward ? 1 : -1;
        //     idx = MathHelper.Mod(idx, ChannelSelectorPopup.ChannelSelectorOrder.Length);
        // } while ((Controller.SelectableChannels & ChannelSelectorPopup.ChannelSelectorOrder[idx]) == 0);
        //
        // SafelySelectChannel(ChannelSelectorPopup.ChannelSelectorOrder[idx]);
    }

    public void SafelySelectChannel(ChatSelectChannel toSelect)
    {
        toSelect = Controller.MapLocalIfGhost(toSelect);
        if ((Controller.SelectableChannels & toSelect) == 0)
            return;

        // TODO: this should just be some default selection when chat channels update.
        // ChatInput.ChannelSelector.Select(toSelect);
    }

    private void OnInputKeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.TextReleaseFocus)
        {
            ChatInput.Input.ReleaseKeyboardFocus();
            ChatInput.Input.Clear();
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelForward)
        {
            CycleChatChannel(true);
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelBackward)
        {
            CycleChatChannel(false);
            args.Handle();
        }
    }

    private void OnTextChanged(LineEditEventArgs args)
    {
        // Update channel select button to correct channel if we have a prefix.
        Controller.UpdateSelectedChannel(this);

        // Warn typing indicator about change
        Controller.NotifyChatTextChange();
    }

    private void OnFocusEnter(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        Controller.NotifyChatFocus(true);
    }

    private void OnFocusExit(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        Controller.NotifyChatFocus(false);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing) return;
        Controller.UnregisterChat(this);
        ChatInput.Input.OnTextEntered -= OnTextEntered;
        ChatInput.Input.OnKeyBindDown -= OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged -= OnTextChanged;
        ChatInput.ChannelSelector.OnChannelSelect -= OnChannelSelect;
    }
}
