using Content.Client._ES.Core;
using Content.Client._ES.SecretIdentity;
using Content.Client.Roles;
using Content.Shared._ES.Auditions.Components;
using Content.Shared.Mind;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._ES.Stagehand.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESObservablePlayerButton : ContainerButton
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    private readonly JobSystem _job;
    private readonly ESSecretIdentitySystem _secretIdentity;
    private readonly SpriteSystem _sprite;

    public ESObservablePlayerButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _job = _entityManager.System<JobSystem>();
        _secretIdentity = _entityManager.System<ESSecretIdentitySystem>();
        _sprite = _entityManager.System<SpriteSystem>();

        ToggleMode = true;
        AddStyleClass(StyleClassButton);
    }

    public void SetEntity(EntityUid uid)
    {
        var metaData = _entityManager.GetComponent<MetaDataComponent>(uid);

        NameLabel.UnsafeSetMarkup(Loc.GetString("es-observe-menu-label-fmt", ("text", metaData.EntityName)));
        JobIcon.Visible = false;
    }

    public void SetPlayer(Entity<MindComponent, ESCharacterComponent> ent)
    {
        var (uid, mind, character) = ent;

        var secretIdentity = _secretIdentity.GetSecretIdentityOrNull((uid, mind));
        var organization = _secretIdentity.GetOrganizationOrNull((uid, mind));

        NameLabel.UnsafeSetMarkup(Loc.GetString("es-observe-menu-label-fmt", ("text", character.Name)));

        if (_job.MindTryGetJob(uid, out var job))
        {
            JobIcon.Texture = _sprite.Frame0(_prototype.Index(job.Icon).Icon);
            JobIcon.ToolTip = job.LocalizedName;
        }

        if (_prototype.TryIndex(secretIdentity, out var secretIdentityPrototype))
            SecretIdentityLabel.UnsafeSetMarkup(Loc.GetString("es-observe-menu-label-fmt", ("text", Loc.GetString(secretIdentityPrototype.Name))), secretIdentityPrototype.Color);

        if (_prototype.TryIndex(organization, out var organizationPrototype)
            && _prototype.TryIndex(organizationPrototype.MetaIcon, out var organizationIcon))
        {
            OrganizationIcon.Texture = _sprite.Frame0(organizationIcon.Icon);
            OrganizationIcon.ToolTip = Loc.GetString(organizationPrototype.Name);
        }
    }
}

