- type: entityTable
  id: ESFillClosetChef
  table: !type:AllSelector
    children:
    - id: MonkeyCubeBox
    - id: SprayBottleWater
    - id: ReagentContainerSugar
    - id: ReagentContainerFlour
    - id: DrinkSoyMilkCarton
    - id: FoodCondimentBottleEnzyme
    - !type:AllSelector
      rolls: 2
      children:
      - id: DrinkMilkCarton
      - id: ReagentContainerFlour
      - id: BoxMousetrap
    - !type:AllSelector
      rolls: 3
      children:
      - id: FoodCondimentPacketSalt
      - id: FoodCondimentPacketPepper
