- type: job
  id: ESDoctor
  parent: ESBaseJobProfessionalNaming
  name: ESjob-name-doctor
  description: ESjob-description-doctor
  playTimeTracker: ESJobDoctor
  startingGear: ESDoctorGear
  icon: "JobIconMedicalDoctor"
  access:
  - Medical
  - Maintenance
  - Chemistry

- type: startingGear
  id: ESDoctorGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: MedicalPDA
    gloves: ClothingHandsGlovesColorBlue
    head: ClothingHeadHatSurgcapBlue
    ears: ClothingHeadsetMedical
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    outerClothing: ClothingOuterCoatLabOpened
    back: ClothingBackpack
  storage:
    back:
    - ESBoxSurvivalMedical

- type: chameleonOutfit
  id: ESDoctor
  job: ESDoctor
  hidden: false
