using System.Diagnostics.CodeAnalysis;
using System.Text;
using Content.Client._ES.UI.Controls.Layout;
using Content.Client.Guidebook.Richtext;
using Content.Shared._ES.SecretIdentity;
using Content.Shared._ES.Tips;
using Content.Shared.Roles;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._ES.Guidebook.Controls;

/// <summary>
///     Renders a panel with a list of tips, sourced from a secret identity prototype, organization prototype, job prototype,
///     or any combination of the three (which will just combine the tips together).
/// </summary>
/// <remarks>
///     Tips inserted in this way should also ideally be present in the main tips dataset.
/// </remarks>
[GenerateTypedNameReferences, UsedImplicitly]
public sealed partial class ESGuideTipsEmbed : VStack, IDocumentTag
{
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private ILogManager _log = default!;
    [Dependency] private ESTipsManager _tips = default!;

    private ISawmill _sawmill;

    public ESGuideTipsEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _log.GetSawmill("guidebook.tips");
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        HashSet<ProtoId<ESTipPrototype>> tips = new();
        if (args.TryGetValue("SecretIdentity", out var secretIdentityProto))
        {
            if (!_proto.TryIndex<ESSecretIdentityPrototype>(secretIdentityProto, out var secretIdentity))
            {
                _sawmill.Error($"Secret identity prototype passed to tips embed tag is invalid: {secretIdentityProto}");
                return false;
            }

            tips.UnionWith(secretIdentity.Tips);
        }

        if (args.TryGetValue("Job", out var jobProto))
        {
            if (!_proto.TryIndex<JobPrototype>(jobProto, out var job))
            {
                _sawmill.Error($"Job prototype passed to tips embed tag is invalid: {jobProto}");
                return false;
            }

            tips.UnionWith(job.Tips);
        }

        if (args.TryGetValue("Organization", out var organizationProto))
        {
            if (!_proto.TryIndex<ESOrganizationPrototype>(organizationProto, out var organization))
            {
                _sawmill.Error($"Organization prototype passed to tips embed tag is invalid: {organizationProto}");
                return false;
            }

            tips.UnionWith(organization.Tips);
        }

        if (tips.Count <= 0)
        {
            // this is still valid
            control = this;
            Visible = false;
            return true;
        }

        TipsTitle.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("es-guidebook-tips-embed-title")), tagsAllowed: null);

        // im sure this is linqable with some string method but whatever
        var tipsSb = new StringBuilder();
        foreach (var tip in tips)
        {
            tipsSb.Append(Loc.GetString("es-guidebook-tips-embed-wrap", ("tip", _tips.GetTipText(tip))));
            tipsSb.AppendLine();
        }

        Tips.SetMessage(FormattedMessage.FromMarkupOrThrow(tipsSb.ToString()), tagsAllowed: null);
        control = this;
        return true;
    }
}
