using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Content.Client._ES.UI.Controls.Layout;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Shared._ES.SecretIdentity;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._ES.Guidebook.Controls;

[GenerateTypedNameReferences]
public sealed partial class ESGuideSecretIdentityEmbed : VStack, IDocumentTag, IPrototypeRepresentationControl
{
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private ILogManager _log = default!;

    private ISawmill _sawmill;

    public IPrototype? RepresentedPrototype { get; set; }

    public ESGuideSecretIdentityEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _log.GetSawmill("guidebook.secret_identity");
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        if (!args.TryGetValue("SecretIdentity", out var proto))
        {
            _sawmill.Error("Secret identity embed tag is missing prototype argument");
            control = null;
            return false;
        }

        if (!_proto.TryIndex<ESSecretIdentityPrototype>(proto, out var secretIdentity))
        {
            _sawmill.Error($"Secret identity prototype passed to embed tag is invalid: {proto}");
            control = null;
            return false;
        }

        var nameMsg = FormattedMessage.FromMarkupOrThrow(
            Loc.GetString("es-guidebook-secret-identity-embed-name",
                ("color", secretIdentity.Color),
                ("name", Loc.GetString(secretIdentity.Name))));
        SecretIdentityName.SetMessage(nameMsg, tagsAllowed: null);

        var descMsg = FormattedMessage.FromMarkupOrThrow(
            Loc.GetString("es-guidebook-secret-identity-embed-description",
                ("description", Loc.GetString(secretIdentity.Description))));
        SecretIdentityDescription.SetMessage(descMsg, tagsAllowed: null);

        var jobsList = ContentLocalizationManager.FormatList(secretIdentity.ProhibitedJobs.Select(p => _proto.Index(p).LocalizedName).ToList());
        var prohibitedJobsMsg = FormattedMessage.FromMarkupOrThrow(
            Loc.GetString("es-guidebook-secret-identity-embed-prohibited-jobs", ("jobs", jobsList)));
        SecretIdentityProhibitedJobs.SetMessage(prohibitedJobsMsg, tagsAllowed: null);

        if (jobsList.Length == 0)
            SecretIdentityProhibitedJobs.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("es-guidebook-secret-identity-embed-prohibited-jobs-none")), tagsAllowed: null);

        RepresentedPrototype = secretIdentity;
        control = this;
        return true;
    }
}
