- type: job
  id: ESDetective
  parent: ESBaseJobSecurityNaming
  name: ESjob-name-detective
  description: ESjob-description-detective
  playTimeTracker: ESJobDetective
  startingGear: ESDetectiveGear
  icon: "JobIconDetective"
  access:
  - Security
  - Brig
  - Detective
  - External
  special:
  - !type:AddComponentSpecial
    components:
    - type: ActionGrant
      actions:
      - ActionJobHunch
    - type: ESHunch

- type: startingGear
  id: ESDetectiveGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: DetectivePDA
    gloves: ClothingHandsGlovesForensic
    ears: ClothingHeadsetSecurity
    head: ClothingHeadHatFedoraBrown
    neck: ClothingNeckTieDet
    jumpsuit: ClothingUniformJumpsuitDetective
    outerClothing: ESClothingOuterCoatDetectiveLoadout
    back: ClothingBackpack
  storage:
    back:
    - ESBoxSurvival
    - ForensicPad
    - ForensicScanner

- type: chameleonOutfit
  id: ESDetective
  job: ESDetective
  hidden: false
