using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Cargo.Requests;
using Content.Shared._ES.Cargo.Requests.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Cargo.Requests.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESCargoRequestConsoleWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public event Action<string>? OnDepartmentIdChanged;

    public ESCargoRequestConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        DepartmentIdButtonEdit.OnPressed += _ =>
        {
            IdDisplayContainer.Visible = false;
            IdEditContainer.Visible = true;

            DepartmentIdEdit.GrabKeyboardFocus();
        };

        DepartmentIdEdit.OnFocusExit += _ =>
        {
            OnDepartmentIdChanged?.Invoke(DepartmentIdEdit.Text);
            IdDisplayContainer.Visible = true;
            IdEditContainer.Visible = false;
        };
        DepartmentIdEdit.OnTextEntered += _ => DepartmentIdEdit.ReleaseKeyboardFocus();
        DepartmentIdEdit.IsValid = ESSharedCargoRequestSystem.ValidateDepartmentId;
    }

    public void Update(EntityUid owner)
    {
        if (!_entityManager.TryGetComponent<ESCargoRequestConsoleComponent>(owner, out var comp))
            return;
        DepartmentIdLabel.SetMarkup($"[font=\"Monospace\"]{comp.DepartmentString}[/font]");
        DepartmentIdEdit.Text = comp.DepartmentString;

        CreateRequestButton.Visible = !comp.MasterConsole;
    }
}

