# Base prototypes

## Recipes

# Tools
- type: latheRecipe
  parent: BaseToolRecipe
  id: Handcuffs
  result: Handcuffs
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseToolRecipe
  id: Flash
  result: Flash
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100
