using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._ES.Lobby;

[GenerateTypedNameReferences]
public sealed partial class ESLobbyClosedPopupWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IUriOpener _uri = default!;

    public ESLobbyClosedPopupWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var discordLink = _cfg.GetCVar(CCVars.InfoLinksDiscord);
        DiscordButton.OnPressed += _ => _uri.OpenUri(_cfg.GetCVar(CCVars.InfoLinksDiscord));
        DiscordButton.Disabled = discordLink == string.Empty;
    }
}
