- type: job
  id: ESAtmosphericTechnician
  parent: ESBaseJobProfessionalNaming
  name: ESjob-name-atmostech
  description: ESjob-description-atmostech
  playTimeTracker: ESJobAtmosphericTechnician
  startingGear: ESAtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: ESAtmosphericTechnicianGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: AtmosPDA
    ears: ClothingHeadsetEngineering
    jumpsuit: ClothingUniformJumpsuitAtmos
    back: ClothingBackpack
  storage:
    back:
    - ESBoxSurvival

- type: chameleonOutfit
  id: ESAtmosphericTechnician
  job: ESAtmosphericTechnician
  hidden: false
