- type: entity
  id: ESMindRoleMask
  name: Mask Role
  components:
  - type: MindRole
  - type: ESSecretIdentityRole

- type: entity
  id: ESBaseMaskObjective
  abstract: true
  components:
  - type: ESObjective
  - type: ESSecretIdentityObjective
  - type: ESStagehandAware
