using System.Linq;
using Content.Client._ES.Core;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Nuke.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Nuke.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESCryptoNukeConsoleWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPlayerManager _player = default!;
    private readonly ESCryptoNukeSystem _cryptoNuke;
    private readonly TransformSystem _transform;

    public event Action? OnHackButtonPressed;
    public event Action? OnOverrideButtonPressed;

    public ESCryptoNukeConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _cryptoNuke = _entityManager.System<ESCryptoNukeSystem>();
        _transform = _entityManager.System<TransformSystem>();

        HackButton.OnPressed += _ => OnHackButtonPressed?.Invoke();
        OverrideButton.OnPressed += _ => OnOverrideButtonPressed?.Invoke();

        HeaderLabel.UnsafeSetMarkup(Loc.GetString("es-cryptonuke-ui-label-disk-header"));
        FlavorLabel.UnsafeSetMarkup(Loc.GetString("es-cryptonuke-ui-label-flavor"));

        NavMap.WallColor = Color.Red;
        NavMap.TileColor = Color.Black;
        NavMap.Blinks = false;
    }

    public void Update(EntityUid owner, ESCryptoNukeConsoleBuiState? state = null)
    {
        if (!_entityManager.TryGetComponent<ESCryptoNukeConsoleComponent>(owner, out var comp))
            return;

        NavMap.MapUid = _entityManager.GetComponent<TransformComponent>(owner).GridUid;
        NavMap.ForceNavMapUpdate();

        if (_player.LocalEntity is not { } player)
            return;

        HackButton.Visible = _cryptoNuke.CanPotentiallyHack(player);

        if (state != null)
        {
            NavMap.TrackedCoordinates.Clear();
            NavMap.TrackedCoordinates = state.DiskLocations
                .Select(c => (_entityManager.GetCoordinates(c), (true, Color.White)))
                .ToDictionary();

            var diskLocations = state.DiskLocations
                .Select(c => _transform.ToWorldPosition(c));
            LocationsLabel.UnsafeSetMarkup(string.Join('\n',
                diskLocations
                    .Select(c => Loc.GetString("es-cryptonuke-ui-label-disk-fmt", ("x", c.X), ("y", c.Y)))));

            HackButton.Disabled = !_cryptoNuke.CanHack(player) || comp.Compromised;
            OverrideButton.Disabled = !comp.CanOverrideWarpDriveSecurity || comp.WarpDriveSecurityOverridden;
        }

        if (!HackButton.Disabled)
        {
            HackButton.ToolTip = Loc.GetString("es-cryptonuke-ui-button-go-tooltip");
        }
        else
        {
            HackButton.ToolTip = comp.Compromised
                ? Loc.GetString("es-cryptonuke-ui-button-already-hacked-tooltip")
                : Loc.GetString("es-cryptonuke-ui-button-hack-tooltip");
        }

        if (!OverrideButton.Disabled)
        {
            OverrideButton.ToolTip = Loc.GetString("es-cryptonuke-ui-button-override-tooltip");
        }
        else if (!_cryptoNuke.CanPotentiallyOverride(player))
        {
            OverrideButton.ToolTip = Loc.GetString("es-cryptonuke-ui-button-override-cant-override-tooltip");
        }
        else
        {
            OverrideButton.ToolTip = comp.WarpDriveSecurityOverridden
                ? Loc.GetString("es-cryptonuke-ui-button-override-already-overriden-tooltip")
                : Loc.GetString("es-cryptonuke-ui-button-override-disabled-tooltip");
        }

        CompromisedLabel.UnsafeSetMarkup(Loc.GetString("es-cryptonuke-ui-label-compromised", ("state", comp.Compromised)));

        var codes = state?.Codes is { Count: > 0}
            ? string.Join(",", state.Codes)
            : Loc.GetString("es-cryptonuke-ui-label-code-placeholder");
        CodesLabel.UnsafeSetMarkup(Loc.GetString("es-cryptonuke-ui-label-code-header", ("codes", codes)));
    }
}
