using Content.Shared._ES.Mapping;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Mapping;

[GenerateTypedNameReferences]
public sealed partial class ESMappingControls : UIWidget
{
    public ESMappingControls()
    {
        RobustXamlLoader.Load(this);

        var uiController = UserInterfaceManager.GetUIController<ESMappingUIController>();
        MoveButton.OnPressed += _ => uiController.OnMoveModePressed();
        SelectButton.OnPressed += _ => uiController.OnSelectModePressed();
    }

    public void SetState(ESSelectionState state)
    {
        if (state is ESSelectionState.Disabled)
        {
            MoveButton.Pressed = true;
        }
        else
        {
            SelectButton.Pressed = true;
        }
    }

    public void SetDisabled(bool disabled)
    {
        MoveButton.Disabled = disabled;
        SelectButton.Disabled = disabled;
    }
}
