using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._ES.Cinematic;

/// <summary>
///     Contains the texture rect for a given cinematic, if one is playing.
/// </summary>
public sealed class CinematicContainer : UIWidget
{
    public AnimatedTextureRect CinematicTexture { get; private set; }

    public CinematicContainer()
    {
        CinematicTexture = new AnimatedTextureRect();
        CinematicTexture.DisplayRect.Stretch = TextureRect.StretchMode.Scale;
        AddChild(CinematicTexture);
        SetPositionLast();
    }

    public void ResetCinematicTexture()
    {
        if (ChildCount != 0)
            RemoveAllChildren();

        CinematicTexture = new AnimatedTextureRect();
        CinematicTexture.DisplayRect.Stretch = TextureRect.StretchMode.Scale;
        AddChild(CinematicTexture);
    }
}
