using Content.Client.UserInterface.Systems.Chat.Widgets;
using Content.Shared.Chat;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Shared.Audio;
using Robust.Shared.Player;
using Robust.Shared.Utility;

namespace Content.Client._ES.Chat;

/// <summary>
///     A chat box with two separate output panels for deadchat messages and all other chat messages.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class StagehandChatBox : ChatBox
{
    protected override void OnMessageAdded(ChatMessage msg)
    {
        Sawmill.Debug($"{msg.Channel}: {msg.Message}");
        if (!ChatInput.FilterButton.Popup.IsActive(msg.Channel))
        {
            return;
        }

        if (msg is { Read: false, AudioPath: { } })
            EntManager.System<AudioSystem>().PlayGlobal(msg.AudioPath, Filter.Local(), false, AudioParams.Default.WithVolume(msg.AudioVolume));

        msg.Read = true;

        var color = msg.MessageColorOverride ?? msg.Channel.TextColor();

        if (msg.Channel == ChatChannel.Dead)
            AddStagehandLine(msg.WrappedMessage, color);
        else
            AddLine(msg.WrappedMessage, color);
    }

    public override void Repopulate()
    {
        StagehandContents.Clear();
        base.Repopulate();
    }

    protected override void OnChannelFilter(ChatChannel channel, bool active)
    {
        StagehandContents.Clear();
        base.OnChannelFilter(channel, active);
    }

    public void AddStagehandLine(string message, Color color)
    {
        var formatted = new FormattedMessage(3);
        formatted.PushColor(color);
        formatted.AddMarkupOrThrow(message);
        formatted.Pop();
        StagehandContents.AddMessage(formatted, tagsAllowed: null);
    }
}
