using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Content.Shared.Chat;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Audio;
using Robust.Shared.Player;
using Robust.Shared.Utility;

namespace Content.Client._ES.Chat;

/// <summary>
///     A chat box with two separate output panels for deadchat messages and all other chat messages.
/// </summary>
public sealed partial class StagehandChatBox : ChatBox
{
    public PanelContainer StagehandChatWindowPanel;
    public OutputPanel StagehandContents;

    public StagehandChatBox()
    {
        Orientation = LayoutOrientation.Vertical;

        StagehandContents = new OutputPanel()
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            Margin = new(8, 8, 8, 4),
            ShowScrollDownButton = true,
        };

        // this should be done with xaml but uhh i was having extremely strange issues with that
        StagehandChatWindowPanel = new PanelContainer()
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            SizeFlagsStretchRatio = 0.7f,
            Margin = new(0,0,0, 10)
        };
        StagehandChatWindowPanel.AddStyleClass("StyleNano.StyleClassChatPanel");
        AddChild(StagehandChatWindowPanel);
        StagehandChatWindowPanel.SetPositionFirst();
        StagehandChatWindowPanel.AddChild(StagehandContents);
    }

    protected override void OnMessageAdded(ChatMessage msg)
    {
        Sawmill.Debug($"{msg.Channel}: {msg.Message}");
        if (!ChatInput.FilterButton.Popup.IsActive(msg.Channel))
        {
            return;
        }

        if (msg is { Read: false, AudioPath: { } })
            EntManager.System<AudioSystem>().PlayGlobal(msg.AudioPath, Filter.Local(), false, AudioParams.Default.WithVolume(msg.AudioVolume));

        msg.Read = true;

        var color = msg.MessageColorOverride ?? msg.Channel.TextColor();

        if (msg.Channel == ChatChannel.Dead)
            AddStagehandLine(msg.WrappedMessage, color);
        else
            AddLine(msg.WrappedMessage, color);
    }

    public override void Repopulate()
    {
        StagehandContents.Clear();
        base.Repopulate();
    }

    protected override void OnChannelFilter(ChatChannel channel, bool active)
    {
        StagehandContents.Clear();
        base.OnChannelFilter(channel, active);
    }

    public void AddStagehandLine(string message, Color color)
    {
        var formatted = new FormattedMessage(3);
        formatted.PushColor(color);
        formatted.AddMarkupOrThrow(message);
        formatted.Pop();
        StagehandContents.AddMessage(formatted, tagsAllowed: null);
    }
}
