using Content.Shared._ES.Voting.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Voting.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESVoteControl : PanelContainer
{
    public ESVoteControl()
    {
        RobustXamlLoader.Load(this);
    }

    public ESVoteControl(Entity<ESVoteComponent> vote, IEntityManager entityManager)
    {
        RobustXamlLoader.Load(this);

        VoteNameLabel.Text = entityManager.GetComponentOrNull<MetaDataComponent>(vote)?.EntityName ?? "Unknown";

        foreach (var option in vote.Comp.VoteOptions)
        {
            var button = new Button
            {
                Text = option.DisplayString,
                HorizontalExpand = true,
            };
            OptionsContainer.AddChild(button);
        }
    }
}

