using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Voting;
using Content.Shared._ES.Voting.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Voting.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESVotingWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly ESVoteSystem _vote;

    public event Action<Entity<ESVoteComponent>, ESVoteOption>? OnVoteChanged;

    public ESVotingWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _vote = _entityManager.System<ESVoteSystem>();
    }

    public void Update(EntityUid owner)
    {
        VotesContainer.Children.Clear();
        foreach (var vote in _vote.EnumerateVotes())
        {
            var voteControl = new ESVoteControl(vote, _entityManager);
            voteControl.OnVoteChanged += OnVoteChanged;
            VotesContainer.AddChild(voteControl);
        }
    }
}

