using Content.Shared._ES.Voting;
using Content.Shared._ES.Voting.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Voting.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESVoteControl : PanelContainer
{
    public event Action<Entity<ESVoteComponent>, ESVoteOption>? OnVoteChanged;

    public ESVoteControl()
    {
        RobustXamlLoader.Load(this);
    }

    public ESVoteControl(Entity<ESVoteComponent> vote, IEntityManager entityManager)
    {
        RobustXamlLoader.Load(this);

        VoteNameLabel.Text = entityManager.GetComponentOrNull<MetaDataComponent>(vote)?.EntityName ?? string.Empty;

        var group = new ButtonGroup();

        foreach (var (option, votes) in vote.Comp.Votes)
        {
            var voteCount = votes.Count;

            var button = new ContainerButton
            {
                StyleClasses = { ContainerButton.StyleClassButton },
                ToggleMode = true,
                Group = group,
                Children =
                {
                    new RichTextLabel
                    {
                        Text = Loc.GetString("es-voter-ui-button-text-option-format", ("option", option.DisplayString), ("count", voteCount)),
                    },
                },
            };
            button.OnPressed += _ =>
            {
                OnVoteChanged?.Invoke(vote, option);
            };

            OptionsContainer.AddChild(button);
        }
    }
}

