using Content.Client.Stylesheets;
using Content.Shared._ES.Voting;
using Content.Shared._ES.Voting.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Voting.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESVoteControl : PanelContainer
{
    public event Action<Entity<ESVoteComponent>, ESVoteOption>? OnVoteChanged;

    public EntityUid Vote { get; set; } = EntityUid.Invalid;

    public ESVoteControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(Entity<ESVoteComponent> vote, IEntityManager entityManager, EntityUid owner)
    {
        if (!entityManager.EntityExists(vote))
            return;

        var netOwner = entityManager.GetNetEntity(owner);

        VoteNameLabel.Text = entityManager.GetComponentOrNull<MetaDataComponent>(vote)?.EntityName ?? string.Empty;

        var group = new ButtonGroup();

        if (OptionsContainer.ChildCount == 0)
        {
            foreach (var (option, votes) in vote.Comp.Votes)
            {
                var button = new ESVoteButton
                {
                    Group = group,
                    Option = option,
                    Pressed = votes.Contains(netOwner),
                };

                button.OnPressed += _ =>
                {
                    OnVoteChanged?.Invoke(vote, option);
                };

                OptionsContainer.AddChild(button);
            }
            OptionsContainer.InvalidateArrange();
        }

        // TODO: this doesn't work.
        foreach (var child in OptionsContainer.Children)
        {
            if (child is ESVoteButton voteButton)
            {
                var votes = vote.Comp.Votes.GetValueOrDefault(voteButton.Option) ?? [];
                voteButton.Label.Text = Loc.GetString("es-voter-ui-button-text-option-format",
                    ("option", voteButton.Option.DisplayString),
                    ("count", votes.Count));
            }
        }
    }

    private sealed class ESVoteButton : ContainerButton
    {
        public RichTextLabel Label { get; }
        public ESVoteOption Option { get; set; } = default!;

        public ESVoteButton()
        {
            StyleClasses.Add(StyleClassButton);
            StyleClasses.Add(StyleBase.ButtonOpenBoth);
            ToggleMode = true;

            Label = new RichTextLabel();
            AddChild(Label);
        }
    }
}
