using Content.Client._ES.Core;
using Content.Shared._ES.Core;
using Content.Shared._ES.Objectives.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._ES.Objectives.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESObjectiveControl : BoxContainer
{
    [Dependency] private EntityManager _ent = default!;
    private readonly ESObjectiveSystem _objective;
    private readonly SpriteSystem _sprite;

    private EntityUid Objective { get; set; }

    public ESObjectiveControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _objective = _ent.System<ESObjectiveSystem>();
        _sprite = _ent.System<SpriteSystem>();

        _objective.OnObjectiveProgressChanged += OnProgressChanged;
    }

    private void OnProgressChanged(Entity<ESObjectiveComponent> obj)
    {
        if (obj.Owner != Objective)
            return;
        SetObjective(Objective); // update
    }

    public void SetObjective(EntityUid objective)
    {
        Objective = objective;

        var metaData = _ent.GetComponent<MetaDataComponent>(objective);
        TitleLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-objective-title-fmt", ("title", metaData.EntityName)));
        DescriptionLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-objective-desc-fmt", ("text", metaData.EntityDescription)));

        Icon.Texture = _sprite.Frame0(_objective.GetIcon(objective));
        Icon.Progress = _objective.GetProgress(objective);

        if (_ent.TryGetComponent<ESObjectiveDescriptorComponent>(objective, out var descriptor))
        {
            OwnerPanel.Visible = true;

            OwnerPanel.ModulateSelfOverride = descriptor.Color;

            OwnerLabel.Text = descriptor.Text;
            OwnerLabel.FontColorOverride = descriptor.Color.GetContrastTextColor();

            if (!string.IsNullOrWhiteSpace(descriptor.Tooltip))
            {
                var tooltip = new Tooltip
                {
                    MaxWidth = 400,
                };
                tooltip.SetMessage(FormattedMessage.FromMarkupPermissive(descriptor.Tooltip));
                TooltipSupplier = _ => tooltip;
            }
        }
        else
        {
            OwnerPanel.Visible = false;
        }

        ResizeTitle();
    }

    private void ResizeTitle()
    {
        TitleLabel.MaxWidth = Header.Width - OwnerPanel.Width - Icon.Width;
    }

    protected override void Resized()
    {
        base.Resized();

        ResizeTitle();
    }
}

