- type: job
  id: ESClown
  name: ESjob-name-clown
  description: ESjob-description-clown
  playTimeTracker: ESJobClown
  startingGear: ESClownGear
  icon: "JobIconClown"
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: SleepEmitSound
      snore: /Audio/Voice/Misc/silly_snore.ogg
      interval: 10
  - !type:AddImplantSpecial
    implants: [ SadTromboneImplant ]

- type: startingGear
  id: ESClownGear
  equipment:
    shoes: ClothingShoesClown
    mask: ClothingMaskClown
    id: ClownPDA
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitClown
    back: ClothingBackpackClown
    pocket1: BikeHorn
  storage:
    back:
    - ESBoxHug
    - RubberStampClown
    - CrayonRainbow

- type: chameleonOutfit
  id: ESClown
  job: ESClown
  hidden: false
