- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        tableId: ESFillLockerSecurity

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        tableId: ESFillLockerDetective

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        tableId: FillClosetBomb

- type: entityTable
  id: FillClosetBomb
  table:
    all:
    - id: Wirecutter
    - id: Screwdriver
    - id: Multitool
      prob: 0.5
