- type: entity
  id: LockerBoozeFilled
  suffix: Filled
  parent: LockerBooze
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        tableId: ESFillLockerBooze

- type: entity
  id: ClosetChefFilled
  suffix: Filled
  parent: ClosetChef
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        tableId: ESFillClosetChef

- type: entity
  id: ClosetJanitorFilled
  suffix: Filled
  parent: ClosetJanitor
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetJanitor

- type: entityTable
  id: FillClosetJanitor
  table: !type:AllSelector
    children:
    - id: MopItem
    - id: BoxLightMixed
    - id: WetFloorSign
      amount: 1, 3
    - pick:
        all:
        - id: WetFloorSign
        - id: Mousetrap
        - id: TrashBag
        - tableId: ESSoap
        - id: FlashlightLantern
        - id: Plunger
        - id: Bucket
      amount: 3
