- type: entity
  id: ESBaseStationArrivals
  abstract: true
  components:
  - type: ESStationArrivals

- type: entity
  id: ESBaseStationNeutral
  parent:
  - BaseStation
  - BaseStationNews
  - BaseStationJobsSpawning
  - BaseStationRecords
  - BaseStationAlertLevels
  - BaseStationAllEventsEligible
  - ESBaseStationArrivals
  categories: [ HideSpawnMenu ]
  components:
  - type: Transform
  - type: ESProducer
