- type: entity
  id: ESBaseStationArrivals
  abstract: true
  components:
  - type: ESStationArrivals

- type: entity
  id: ESBaseStationEvacuation
  abstract: true
  components:
  - type: ESEvacStation
  - type: StationEmergencyShuttle

- type: entity
  id: ESBaseStationStoreroom
  abstract: true
  components:
  - type: ESStoreroomStation
  - type: ESCargoRequestStation

- type: entity
  id: ESBaseStationNeutral
  parent:
  - BaseStation
  - BaseStationNews
  - BaseStationJobsSpawning
  - BaseStationRecords
  - BaseStationAlertLevels
  - BaseStationAllEventsEligible
  - ESBaseStationArrivals
  - ESBaseStationStoreroom
  categories: [ HideSpawnMenu ]
  components:
  - type: Transform
  - type: ESProducer
