- type: entity
  id: ESBaseStationNeutral
  parent: StandardNanotrasenStation
  categories: [ HideSpawnMenu ]
  components:
  - type: Transform
  - type: GridSpawn
    groups:
      trade: !type:GridSpawnGroup
        addComponents:
        - type: ProtectedGrid
        - type: TradeStation
        paths:
        - /Maps/Shuttles/trading_outpost.yml
