using Content.Client._ES.Auditions;
using Content.Client._ES.Core;
using Content.Shared._Citadel.Utilities;
using Content.Shared.GameTicking;
using Content.Shared.Roles;
using Content.Shared.Station;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._ES.Spawning.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESJobDisplay : BoxContainer
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private readonly ESAuditionsSystem _auditions;
    private readonly SharedStationSpawningSystem _stationSpawning;

    private ProtoId<JobPrototype> _jobId;
    private EntityUid _doll;

    public ESJobDisplay()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _auditions = _entityManager.System<ESAuditionsSystem>();
        _stationSpawning = _entityManager.System<SharedStationSpawningSystem>();

        SetJob(SharedGameTicker.FallbackOverflowJob);
    }

    public void SetJob(ProtoId<JobPrototype> job)
    {
        _jobId = job;

        var jobProto = _prototypeManager.Index(job);

        NameLabel.Text = Loc.GetString(jobProto.Name);
        DescriptionLabel.UnsafeSetMarkup(jobProto.Description == null
            ? string.Empty
            : Loc.GetString(jobProto.Description));


        var seed = new RngSeed().SeedForStep(job.Id.GetHashCode() + _player.LocalEntity?.Id ?? 0);
        var random = seed.IntoRandomizer();
        var defaultDude = _auditions.RandomProfile(random, jobProto.SpeciesOverride, out _);

        _entityManager.DeleteEntity(_doll);
        _doll = _stationSpawning.SpawnPlayerMob(null, jobProto, defaultDude, null);
        JobView.SetEntity(_doll);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        SetJob(_jobId);
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _entityManager.DeleteEntity(_doll);
    }
}

